#ifndef __CONSTANTES__H__
#define __CONSTANTES__H__

#define CONSTANTE_CONSTANTE_ENTERA						0
#define CONSTANTE_CONSTANTE_REAL						1
#define CONSTANTE_CONSTANTE_STRING						2
#define CONSTANTE_CONSTANTE_STRING_SUPERA				3
#define CONSTANTE_IF									4
#define CONSTANTE_ENDIF									5
#define CONSTANTE_WHILE									6
#define CONSTANTE_DO									7
#define CONSTANTE_ENDWHILE								8
#define CONSTANTE_IN									9
#define CONSTANTE_LECTURA								10
#define CONSTANTE_ESCRITURA								11
#define CONSTANTE_VAR									12
#define CONSTANTE_ENDVAR								13
#define CONSTANTE_SIMBOLO_ESPECIAL_CORCHETE_ABRE		14
#define CONSTANTE_SIMBOLO_ESPECIAL_CORCHETE_CIERRA		15
#define CONSTANTE_SIMBOLO_ESPECIAL_PARENTESIS_ABRE		16
#define CONSTANTE_SIMBOLO_ESPECIAL_PARENTESIS_CIERRA	17
#define CONSTANTE_SIMBOLO_ESPECIAL_COMA					18
#define CONSTANTE_SIMBOLO_ESPECIAL_DOS_PUNTOS			19
#define CONSTANTE_FUNCION_LONG							20
#define CONSTANTE_TIPO_DATO								21
#define CONSTANTE_OPERADOR_STRING						22
#define CONSTANTE_OPERADOR_NUMERICO_MAS					23
#define CONSTANTE_OPERADOR_NUMERICO_MENOS				24
#define CONSTANTE_OPERADOR_NUMERICO_POR					25
#define CONSTANTE_OPERADOR_NUMERICO_DIVISION			26
#define CONSTANTE_OPERADOR_LOGICO_AND					27
#define CONSTANTE_OPERADOR_LOGICO_OR					28
#define CONSTANTE_OPERADOR_LOGICO_NOT					29
#define CONSTANTE_OPERADOR_COMPARADOR_MENOR				30
#define CONSTANTE_OPERADOR_COMPARADOR_MENOR_IGUAL		31
#define CONSTANTE_OPERADOR_COMPARADOR_MAYOR				32
#define CONSTANTE_OPERADOR_COMPARADOR_MAYOR_IGUAL		33
#define CONSTANTE_OPERADOR_COMPARADOR_IGUAL				34
#define CONSTANTE_OPERADOR_COMPARADOR_DISTINTO			35
#define CONSTANTE_ASIGNACION							36
#define CONSTANTE_COMENTARIO							37
#define CONSTANTE_CARRI_LINE							38
#define CONSTANTE_ESPACIO								39
#define CONSTANTE_PALABRA								40
#define CONSTANTE_UNRECOGNIZED							41
#endif
